# Generated by Django 3.1.7 on 2021-04-05 14:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('profile_picture', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('birth_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('qualification', models.CharField(max_length=200, null=True)),
                ('guardian', models.CharField(max_length=150, null=True)),
                ('is_instuctor', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=12, unique=True)),
            ],
        ),
    ]
