# Generated by Django 3.1.7 on 2021-04-06 15:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_remove_userprofile_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('birth_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('guardian', models.CharField(max_length=150, null=True)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('in_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('birth_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('qualification', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
