# Generated by Django 3.1.7 on 2021-04-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_instructor_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
