# Generated by Django 3.1.7 on 2021-04-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='is_instuctor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_instuctor',
            field=models.BooleanField(default=False),
        ),
    ]
