# Generated by Django 3.1.7 on 2021-04-17 11:33

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210407_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('picture_1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('picture_2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('picture_3', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.instructor')),
            ],
        ),
    ]
