# Generated by Django 3.1.7 on 2021-04-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210417_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='resume',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
