# Generated by Django 3.1.7 on 2021-04-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.ImageField(default='photos\x821\x04\x06\x01.png', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
